[project]
name = ""
version = ""
description = ""
authors = [
    {name = "JamesCurtis", email = "jamescurtis@foxmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

